name: Backed chat CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: none
    steps:
      - uses: actions/checkout@v1
      - name: Instalar & test
        run: |
          npm install
          npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login 
        run: docker login  -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: construir docker
        run: docker build -t back . 
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag back ${{secrets.DOCKER_USER}}/back:latest
      - name: Push
        run: |
          docker push ${{secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest



      